[package]
name = "cognitive-services-speech-sdk-rs"
version = "0.1.2"
authors = ["Adam Bezecny <adam.bezecny@gmail.com>"]
edition = "2018"
description = "Pure Rust binding to Microsoft Speech SDK with thin convenience abstraction."
license = "MIT OR Apache-2.0"
keywords = ["speech", "microsoft", "cognitive", "recognition", "synthesizing"]
categories = ["multimedia", "multimedia::audio", "text-processing"]
exclude = [
    "examples/*"
]
repository = "https://github.com/jabber-tools/cognitive-services-speech-sdk-rs/"
documentation = "https://jabber-tools.github.io/cognitive_services_speech_sdk_rs/doc/0.1.2/cognitive_services_speech_sdk_rs/index.html"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8.3"
tokio = {version = "1.2.0", features = ["full"]} 

[build-dependencies]
bindgen = "0.57.0"